// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kkvvosbyntcfpmluqxmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtrdnZvc2J5bnRjZnBtbHVxeG1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg2NTIwODUsImV4cCI6MjA5NDIyODA4NX0.WsFp54AvAOCkOZ_i9aAHlWJrWSYrK6lH609QAthGXHs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});